
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analise-sentimento
spec:
  selector:
    matchLabels:
      app: analise-sentimento
  template:
    metadata:
      labels:
        app: analise-sentimento
    spec:
      containers:
      - name: analise-sentimento
        image: llzimmer1977/fiapfase05v2:latest  # editar Docker registry, nome e tag da imagem
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 100Mi
        ports:
        - containerPort: 5001  # editar porta

---
apiVersion: v1
kind: Service
metadata:
  name: analise-sentimento
spec:
  type: LoadBalancer
  ports:
  - port: 5001  # editar porta
    targetPort: 5001  # editar porta
    name: "5001"  # editar porta
  selector:
    app: analise-sentimento
